// Generated by CoffeeScript 1.6.3
(function() {
  window.GameLayer = cc.Layer.extend({
    _player: null,
    init: function() {
      var size, tileMap;
      this._super();
      size = cc.Director.getInstance().getWinSize();
      tileMap = cc.TMXTiledMap.create(s_brick_tmx, s_brick);
      this.addChild(tileMap);
      this._player = Player.create();
      this._player.setPosition(size.width / 2, size.height / 2);
      this.addChild(this._player);
      if (sys.capabilities.hasOwnProperty("keyboard")) {
        this.setKeyboardEnabled(true);
      }
      this.scheduleUpdate();
      return true;
    },
    update: function() {
      return this._player.update();
    },
    onKeyUp: function(e) {
      return this._player.onKeyUp(e);
    },
    onKeyDown: function(e) {
      return this._player.onKeyDown(e);
    }
  });

  window.GameScene = cc.Scene.extend({
    onEnter: function() {
      var layer;
      this._super();
      layer = new GameLayer();
      layer.init();
      return this.addChild(layer);
    }
  });

}).call(this);
